### GET /
GET http://localhost:5003

### Register a user POST /AUTH/REGISTER
POST http://localhost:5003/auth/register
Content-Type: application/json

{
    "username": "gilgamesh@gmail.com",
    "password": "123123123"
}

### Login a user POST /AUTH/LOGIN
POST http://localhost:5003/auth/login
Content-Type: application/json

{
    "username": "gilgamesh@gmail.com",
    "password": "123123123"
}

### Fetch all todos GET /TODOS (protected)
GET http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ4NjA4MDc3LCJleHAiOjE3NDg2OTQ0Nzd9.1UPQEcV8GWVBNVNeE_tJHL58d6TNAakFCBy6GMk7yQc

### Create a todo POST /TODOS (protected)
POST http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ4NjA4MDc3LCJleHAiOjE3NDg2OTQ0Nzd9.1UPQEcV8GWVBNVNeE_tJHL58d6TNAakFCBy6GMk7yQc
Content-Type: application/json

{
    "task": "Learn how to use Postman"
}

### Update a todo PUT /TODOS/:id (protected)
PUT http://localhost:5003/todos/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ4NjA4MDc3LCJleHAiOjE3NDg2OTQ0Nzd9.1UPQEcV8GWVBNVNeE_tJHL58d6TNAakFCBy6GMk7yQc
Content-Type: application/json

{
    "completed": 1
}

### Delete a todo DELETE /TODOS/:id (protected)
DELETE http://localhost:5003/todos/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ4NjA2NjAxLCJleHAiOjE3NDg2OTMwMDF9.r508jN79NCtcW1FCQEMVQ8tcLWdBHOfkES5ATHt9iik